

import { Opportunity, TableColumnDef } from './types';

const KAFAAT_RIPC_COLUMNS: TableColumnDef[] = [
  { header: 'Resource', key: 'role', format: 'text' },
  { header: 'Seniority', key: 'seniority', format: 'text' },
  { header: 'FTE Days', key: 'fteDays', format: 'number' },
  { header: 'Cost', key: 'cost', format: 'currency' },
  { header: 'Price', key: 'price', format: 'currency' },
  { header: 'Inc. Margin (30%)', key: 'marginPrice', format: 'currency' },
];

const NWC_COLUMNS: TableColumnDef[] = [
  { header: 'Position', key: 'role', format: 'text' },
  { header: 'Pricing Model', key: 'pricingModel', format: 'text' }, // Blank column
  { header: 'Qty', key: 'qty', format: 'number' },
  { header: 'Unit (Monthly Total)', key: 'unitPrice', format: 'number' },
  { header: 'Total 24M (Sure)', key: 'sureTotal', format: 'number' },
  { header: 'Total 24M (Cntxt)', key: 'cntxtTotal', format: 'sar' },
];

const HEVOLUTION_COLUMNS: TableColumnDef[] = [
  { header: 'Resource', key: 'role', format: 'text' },
  { header: 'Level', key: 'seniority', format: 'text' },
  { header: '1st Month', key: 'fteDays', format: 'number' },
  { header: 'Daily Cost', key: 'dailyCost', format: 'currency' },
  { header: 'Cost per Role', key: 'costPerRole', format: 'currency' },
  { header: 'Price inc. Margin', key: 'marginPrice', format: 'currency' },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'I-02975',
    customer: 'PIF',
    dealValue: 58666.66,
    status: 'Closed-Loss',
    closeDate: '12/24/2025',
    deliveryEngaged: true,
    deliveryPrice: 98000.00,
    partnerPrice: 58666.66,
    partnerName: 'Digital Future',
    issue: 'Commercial Variance',
    notes: 'Initial Delivery estimate $138k. Optimized to $93k. Partner selected at $58k.',
    isHighPriority: true,
    useCase: 'Assessment, planning, and implementation of new environment. Includes network security best practices, migration to GKE setup, and 2 weeks of Hypercare support.',
    deliveryEffort: '10 weeks',
    partnerEffort: '9 weeks',
  },
  {
    id: 'I-03126',
    customer: 'IoT2',
    dealValue: 0, 
    status: 'Active',
    closeDate: '11/30/2025',
    deliveryEngaged: true,
    deliveryPrice: 960166.66,
    partnerPrice: null, 
    partnerName: null,
    issue: 'Commercial Variance',
    notes: 'Client seeking alternative commercial models. Cloud Foundational Large Package.',
    isHighPriority: true,
    useCase: 'Cloud Foundational (Large Package) and Disaster Recovery Professional Services.',
    deliveryEffort: 'N/A',
    partnerEffort: 'N/A',
  },
  {
    id: 'I-03125',
    customer: 'JEDCO',
    dealValue: 263920.00,
    status: 'Active',
    closeDate: '11/30/2025',
    deliveryEngaged: true,
    deliveryPrice: 263920.00,
    partnerPrice: 90000.00,
    partnerName: 'Clear Vision',
    issue: null,
    notes: 'Market comparison: $263k vs $90k.',
    isHighPriority: true,
    useCase: 'Professional Services engagement.',
    deliveryEffort: '5 months',
    partnerEffort: 'N/A',
    resourceTableTitle: 'Landing Zone & Disaster Recovery Estimation',
    resourceDetails: [
      // Landing Zone Section
      { section: 'Landing Zone', role: 'Project Manager', fteDays: 16, totalPrice: 12800.00 },
      { section: 'Landing Zone', role: 'Cloud Architect', fteDays: 16, totalPrice: 20000.00 },
      { section: 'Landing Zone', role: 'Network Engineer', fteDays: 24, totalPrice: 14400.00 },
      { section: 'Landing Zone', role: 'Cloud Engineer', fteDays: 40, totalPrice: 24000.00 },
      { section: 'Landing Zone', role: 'Subtotal (Landing Zone)', fteDays: '', totalPrice: 71200.00, isSummary: true },
      
      // Disaster Recovery Section
      { section: 'Disaster Recovery', role: 'Project Manager', fteDays: 43.2, totalPrice: 47520.00 },
      { section: 'Disaster Recovery', role: 'Cloud Architect', fteDays: 24, totalPrice: 30000.00 },
      { section: 'Disaster Recovery', role: 'Network Engineer', fteDays: 36, totalPrice: 21600.00 },
      { section: 'Disaster Recovery', role: 'Security Engineer', fteDays: 36, totalPrice: 21600.00 },
      { section: 'Disaster Recovery', role: 'Cloud Engineer', fteDays: 120, totalPrice: 72000.00 },
      { section: 'Disaster Recovery', role: 'Subtotal (DR)', fteDays: '', totalPrice: 192720.00, isSummary: true },
    ]
  },
  {
    id: 'I-02744',
    customer: 'Hevolution',
    dealValue: 71680.00,
    status: 'Active',
    closeDate: '2/1/2026',
    deliveryEngaged: true,
    deliveryPrice: 63680.00,
    partnerPrice: null,
    partnerName: null,
    issue: 'Pricing Review',
    notes: 'Project shifted to next year. Delivery aligned on Workloads Migration - Small Package.',
    isHighPriority: true,
    useCase: 'Workloads Migration - Small Package for 20 servers migration.',
    deliveryEffort: '96 days (Total)',
    partnerEffort: 'N/A',
    resourceTableTitle: 'Workload Migration Estimation',
    resourceColumns: HEVOLUTION_COLUMNS,
    resourceDetails: [
      { role: 'Project Manager', seniority: 'Medior', fteDays: 8, dailyCost: 800.00, costPerRole: 6400.00, marginPrice: 9142.86 },
      { role: 'Cloud Engineer', seniority: 'Junior/Medior', fteDays: 20, dailyCost: 600.00, costPerRole: 12000.00, marginPrice: 17142.86 },
      { role: 'Network Engineer', seniority: 'Junior/Medior', fteDays: 12, dailyCost: 600.00, costPerRole: 7200.00, marginPrice: 10285.71 },
      { role: 'Senior Cloud Architect', seniority: 'Senior', fteDays: 8, dailyCost: 1250.00, costPerRole: 10000.00, marginPrice: 14285.71 },
    ]
  },
  {
    id: 'I-02878',
    customer: 'Kafaat',
    dealValue: 112293.74,
    status: 'Active',
    closeDate: '12/30/2025',
    deliveryEngaged: true,
    deliveryPrice: 99657.14,
    partnerPrice: 32250.00,
    partnerName: 'SBM / Omniops',
    issue: 'Commercial Variance',
    notes: 'Opportunity to review Landing Zone delivery model. Comparison points: SBM ($35k) and Omniops ($29.5k).',
    isHighPriority: true,
    useCase: 'Cloud Foundational - Medium Package. Includes Project Manager, Cloud Architect, Network Engineer, and Cloud Engineer.',
    deliveryEffort: '96 days (Total)',
    partnerEffort: '22-25 days',
    resourceTableTitle: 'Delivery Cost Breakdown (Inc Margin)',
    resourceColumns: KAFAAT_RIPC_COLUMNS,
    resourceDetails: [
      { role: 'Project Manager', seniority: 'Senior', fteDays: 16, cost: 1020.00, price: 16320.00, marginPrice: 23314.29 },
      { role: 'Cloud Architect', seniority: 'Senior', fteDays: 16, cost: 1020.00, price: 16320.00, marginPrice: 23314.29 },
      { role: 'Network Engineer', seniority: 'Medior', fteDays: 24, cost: 580.00, price: 13920.00, marginPrice: 19885.71 },
      { role: 'Cloud Engineer', seniority: 'Medior', fteDays: 40, cost: 580.00, price: 23200.00, marginPrice: 33142.86 },
    ]
  },
  {
    id: 'I-02967',
    customer: 'NWC (AI/ML)',
    dealValue: 600000.00,
    status: 'Active',
    closeDate: '12/31/2025',
    deliveryEngaged: true,
    deliveryPrice: 13333333.33, 
    partnerPrice: 6620390.00,   
    partnerName: 'Partner Augmentation',
    issue: 'Commercial Variance',
    notes: 'Model evolved from full delivery to partner augmentation to optimize cost structure.',
    isHighPriority: true,
    useCase: 'AI/ML usecases. Digital Delivery quoted 3 years work initially. Partner brought in for augmentation.',
    deliveryEffort: '36 months',
    partnerEffort: '36 months',
  },
  {
    id: 'I-03027',
    customer: 'NWC (Smart Asst)',
    dealValue: 4100000.00,
    status: 'Active',
    closeDate: '12/31/2025',
    deliveryEngaged: true,
    deliveryPrice: 4912650.00,
    partnerPrice: 2518239.00,
    partnerName: 'Partner',
    issue: 'Commercial Variance',
    notes: 'Augmentation model proposed. Reviewing mix of internal vs partner resources.',
    isHighPriority: true,
    useCase: 'AI Smart Assistant implementation.',
    deliveryEffort: '24 months (450 days)',
    partnerEffort: '24 months',
    resourceTableTitle: 'CNTXT Delivery Resource Plan (24 Months)',
    resourceColumns: NWC_COLUMNS,
    resourceDetails: [
      { role: 'Project Manager', pricingModel: '', qty: 1, unitPrice: 38102, sureTotal: 914448, cntxtTotal: 1856250.00 },
      { role: 'Technical Lead', pricingModel: '', qty: 1, unitPrice: 38938, sureTotal: 934512, cntxtTotal: 2109375.00 },
      { role: 'AI/ML Specialist', pricingModel: '', qty: 2, unitPrice: 73168, sureTotal: 1756032, cntxtTotal: 2362500.00 },
      { role: 'Business Analyst', pricingModel: '', qty: 2, unitPrice: 71066, sureTotal: 1705584, cntxtTotal: 2025000.00 },
      { role: 'UI/UX Designer', pricingModel: '', qty: 1, unitPrice: 33053, sureTotal: 793272, cntxtTotal: 843750.00 },
      { role: 'Data Engineer', pricingModel: '', qty: 1, unitPrice: 38108, sureTotal: 914592, cntxtTotal: 1350000.00 },
      { role: 'BI & Dashboard Developer', pricingModel: '', qty: 2, unitPrice: 68460, sureTotal: 1643040, cntxtTotal: 2362500.00 },
      { role: 'Chatbot Developer', pricingModel: '', qty: 2, unitPrice: 68460, sureTotal: 1643040, cntxtTotal: 1687500.00 },
      { role: 'Front / Back End Developer', pricingModel: '', qty: 1, unitPrice: 38108, sureTotal: 914592, cntxtTotal: 1265625.00 },
      { role: 'AI Engineer', pricingModel: '', qty: 2, unitPrice: 76216, sureTotal: 1829184, cntxtTotal: 2362500.00 },
      // Totals Row
      { role: 'Total (Ex VAT)', pricingModel: '', qty: 0, unitPrice: 0, sureTotal: 13048296.00, cntxtTotal: 18225000.00, isSummary: true },
      { role: 'VAT (15%)', pricingModel: '', qty: 0, unitPrice: 0, sureTotal: 1957244.40, cntxtTotal: 2733750.00, isSummary: true },
      { role: 'Total (Inc VAT)', pricingModel: '', qty: 0, unitPrice: 0, sureTotal: 15005540.40, cntxtTotal: 20958750.00, isSummary: true },
    ]
  },
  {
    id: 'I-00352',
    customer: 'ADF',
    dealValue: 1010833.00,
    status: 'Active',
    closeDate: '3/31/2026',
    deliveryEngaged: true,
    deliveryPrice: 1010833.00,
    partnerPrice: null,
    partnerName: null,
    issue: 'Commercial Variance',
    notes: 'Budgetary estimate review. Estimated cost ~$1m for 12 months.',
    isHighPriority: true,
    useCase: 'Landing zone, Lift and Shift, and DR setup. Budgetary estimate requested.',
    deliveryEffort: '12 months',
    partnerEffort: 'N/A',
  },
  {
    id: 'I-03000',
    customer: 'MOJ',
    dealValue: 200000.00,
    status: 'Active',
    closeDate: 'Unknown',
    deliveryEngaged: true,
    deliveryPrice: 160000.00,
    partnerPrice: null,
    partnerName: null,
    issue: null,
    notes: 'Customer interest confirmed.',
    isHighPriority: false,
    useCase: 'PSF opportunity implementation.',
    deliveryEffort: 'Unknown',
    partnerEffort: 'Unknown',
  },
  {
    id: 'I-02495',
    customer: 'Kifah',
    dealValue: 107351.25,
    status: 'Moved - Lost to partner',
    closeDate: 'Unknown',
    deliveryEngaged: true,
    deliveryPrice: 150000.00,
    partnerPrice: null,
    partnerName: 'Rackspace',
    issue: 'Other',
    notes: 'Partner selected (Rackspace).',
    isHighPriority: false,
    useCase: 'General implementation.',
    deliveryEffort: 'Unknown',
    partnerEffort: 'Unknown',
  },
  {
    id: 'I-02857',
    customer: 'RIPC',
    dealValue: 666332.46,
    status: 'Active',
    closeDate: '1/1/2026',
    deliveryEngaged: true,
    deliveryPrice: 51333.33,
    partnerPrice: null,
    partnerName: null,
    issue: 'Pricing Review',
    notes: 'RFP Response. Small landing zone selected.',
    isHighPriority: false,
    useCase: 'Small Landing Zone. Project Management, Cloud Architecture, Network & Cloud Engineering.',
    deliveryEffort: '48 days (Total)',
    partnerEffort: 'N/A',
    resourceTableTitle: 'Small Landing Zone Estimation',
    resourceColumns: KAFAAT_RIPC_COLUMNS,
    resourceDetails: [
      { role: 'Project Manager', seniority: 'Senior', fteDays: 8, cost: 1020.00, price: 8160.00, marginPrice: 11657.14 },
      { role: 'Cloud Architect', seniority: 'Senior', fteDays: 8, cost: 1020.00, price: 8160.00, marginPrice: 11657.14 },
      { role: 'Network Engineer', seniority: 'Medior', fteDays: 12, cost: 580.00, price: 6960.00, marginPrice: 9942.86 },
      { role: 'Cloud Engineer', seniority: 'Medior', fteDays: 20, cost: 580.00, price: 11600.00, marginPrice: 16571.43 },
    ]
  },
  {
    id: 'N0hR7AAJ',
    customer: 'Aramco Stadium',
    dealValue: 1.00,
    status: 'Active',
    closeDate: 'Unknown',
    deliveryEngaged: false,
    deliveryPrice: null,
    partnerPrice: null,
    partnerName: null,
    issue: 'Process',
    notes: 'Requirement gathering phase alignment needed to ensure proposal accuracy.',
    isHighPriority: true,
    useCase: 'Requirements gathering and scope definition.',
    deliveryEffort: 'N/A',
    partnerEffort: 'N/A',
  }
];

export const formatCurrency = (value: number | null | undefined, currency: 'USD' | 'SAR' | 'dual' = 'USD') => {
  if (value === null || value === undefined) return '-';
  
  if (currency === 'dual') {
     const usdVal = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
     const sarVal = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'SAR', maximumFractionDigits: 0 }).format(value * 3.75);
     return `${usdVal} (${sarVal})`;
  }

  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 0,
  }).format(value);
};

export const formatNumber = (value: number | null | undefined) => {
    if (value === null || value === undefined) return '-';
    // If it's a very large number, it might be a total that we don't want decimals on unless necessary, 
    // but for FTE days (e.g. 43.2), we do want decimals.
    return new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value);
};